// Generated by CoffeeScript 1.3.1
(function() {

  define(["clazzy/DeferredList"], function(DeferredList) {
    var Lib;
    return Lib = {
      deferList: function(list, fireOnOneCallback, fireOnOneErrback, consumeErrors, canceller) {
        var dl;
        dl = new DeferredList();
        dl.run(list, fireOnOneCallback, fireOnOneErrback, consumeErrors, canceller);
        return dl;
      },
      findClass: function(name) {
        'use strict';

        var cls, p, parts, _i, _len;
        if (!window) {
          return null;
        }
        parts = name.split(".");
        cls = window;
        for (_i = 0, _len = parts.length; _i < _len; _i++) {
          p = parts[_i];
          if (!cls[p]) {
            return null;
          }
          cls = cls[p];
        }
        return cls;
      }
    };
  });

}).call(this);
