// Generated by CoffeeScript 1.8.0
(function() {
  define(["clazzy/Exception"], function(Exception) {
    'use strict';
    var TemplateRegistry, _DEFAULT, _registry;
    _DEFAULT = "default";
    _registry = {
      "default": {}
    };
    TemplateRegistry = {
      config: _DEFAULT,
      setConfigTo: function(config) {
        if (!config || "string" !== typeof config) {
          (new Exception("InvalidInputException", "config must be a non null string. Currently: " + config)).Throw();
        }
        this.config = config;
        if (!_registry[this.config]) {
          return _registry[this.config] = {};
        }
      },
      register: function(templateId, templateString) {
        if (!templateId || "string" !== typeof templateId) {
          (new Exception("InvalidInputException", "templateId must be a non null string. Currently: " + templateId)).Throw();
        }
        if (!templateString || "string" !== typeof templateString) {
          (new Exception("InvalidInputException", "templateString must be a non null string. Currently: " + templateString)).Throw();
        }
        return _registry[this.config][templateId] = templateString;
      },
      get: function(templateId) {
        if (!templateId || "string" !== typeof templateId) {
          (new Exception("InvalidInputException", "templateId must be a non null string. Currently: " + templateId)).Throw();
        }
        return _registry[this.config][templateId] || "<div>Template not available</div>";
      }
    };
    return TemplateRegistry;
  });

}).call(this);

//# sourceMappingURL=TemplateRegistry.js.map
