// Generated by CoffeeScript 1.3.1
(function() {

  define(["dojo/main", "util/doh/main", "clazzy/Deferred", "clazzy/When"], function(dojo, doh, Deferred, When) {
    return doh.register("clazzy.tests.When", [
      {
        name: "when_resolvedPromise_doWithReturnValue",
        runTest: function(t) {
          var d, response;
          response = new Deferred();
          response.resolve("ok");
          d = new doh.Deferred();
          return When(response, d.getTestCallback(function(data) {
            return doh.assertEqual("ok", data);
          }));
        }
      }, {
        name: "when_nonPromiseValue_doWithValue",
        runTest: function(t) {
          var response;
          response = "ok";
          return When(response, function(data) {
            return doh.assertEqual("ok", data);
          });
        }
      }
    ]);
  });

}).call(this);
