// Generated by CoffeeScript 1.8.0
(function() {
  define(["clazzy/namelocators/NameLocator"], function(NameLocator) {
    'use strict';
    var TemplateNameLocator, namelocator;
    namelocator = new NameLocator();
    return TemplateNameLocator = {
      configExists: function(config) {
        return namelocator.configExists(config || namelocator.config);
      },
      configIsEmpty: function(config) {
        return namelocator.configIsEmpty(config || namelocator.config);
      },
      getConfig: function() {
        return namelocator.config;
      },
      setConfigTo: function(configname) {
        return namelocator.setConfigTo(configname);
      },
      register: function(templateId, className, config) {
        return namelocator.register(templateId, className, config);
      },
      findTemplate: function(className) {
        return namelocator.findSource(className);
      },
      findClass: function(templateId) {
        return namelocator.findTarget(templateId);
      },
      hasTemplate: function(className) {
        return namelocator.hasSource(className);
      },
      clear: function(all) {
        return namelocator.clear(all);
      }
    };
  });

}).call(this);

//# sourceMappingURL=TemplateNameLocator.js.map
